{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: freqtrade
spec:
  rules:
  - host: localhost
    http:
      paths:
      {{- if (and .Values.bot.enabled .Values.config.api_server.enabled) }}
      - path: /
        backend:
          serviceName: freqtrade
          servicePort: 8080
      {{- end }}
      {{- if (and .Values.backtesting.results.enable_export .Values.backtesting.results.reader_enabled) }}
      - path: /results
        backend:
          serviceName: results-reader
          servicePort: 80
      {{- end }}
---
{{- end }}